#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then 
xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --right-of eDP1
fi

bspc monitor eDP1 -d i ii iii iv
bspc monitor HDMI1 -d v vi vii viii

picom &

/home/yan/.config/polybar/launch.sh & 

wal -R & 

$HOME/.config/conky/conky-startup.sh 

# bspc monitor -d I II III IV V
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10


bspc config border_width         2
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
